version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: daily
    groups:
      homeassistant:
        patterns:
          - "homeassistant"
          - "pytest-homeassistant-custom-component"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
