"""Constants for pitboss."""

from datetime import timedelta
from logging import Logger, getLogger

LOGGER: Logger = getLogger(__package__)

NAME = "PitBoss"
DOMAIN = "pitboss"
MANUFACTURER = NAME
PING_INTERVAL = timedelta(seconds=30)
PROTOCOL_WSS = "wss"
PROTOCOL_BLE = "ble"
ALL_PROTOCOLS = (PROTOCOL_BLE, PROTOCOL_WSS)
DEFAULT_PROTOCOL = PROTOCOL_WSS
DEFAULT_MIN_TEMP = 180
DEFAULT_MAX_TEMP = 500
DEFAULT_PROBE_MIN_TEMP = 50
DEFAULT_PROBE_MAX_TEMP = 250
DEFAULT_PROBE_FAHRENHEIT_STEP = 1
DEFAULT_PROBE_CELSIUS_STEP = 1
