#!/usr/bin/env python3
"""Generates docs/SUPPORTED_GRILLS.md from pytboss's grill definitions.

This maps each grill model supported by the `pytboss` library to the
Home Assistant entities/features this integration will expose for it
(lights, meat probes, primer motor, recipe mode, temperature range).

Run manually with:

    python3 -m scripts.generate_grill_docs

This is also run automatically by the "Update grill docs" GitHub Actions
workflow whenever the `pytboss` dependency version is bumped (e.g. by
Dependabot), keeping docs/SUPPORTED_GRILLS.md in sync without manual effort.
"""

from pathlib import Path

from pytboss import grills

REPO_ROOT = Path(__file__).parent.parent
OUTPUT = REPO_ROOT / "docs" / "SUPPORTED_GRILLS.md"

HEADER = """\
# Supported Grills

This page is auto-generated from the [`pytboss`](https://github.com/dknowles2/pytboss)
library's grill definitions. It maps every supported grill model to the
Home Assistant features/entities this integration will expose for it.

Do not edit this file by hand — run `python3 -m scripts.generate_grill_docs`
(this happens automatically when the `pytboss` dependency is updated).

| Model | Min Temp (°F) | Max Temp (°F) | Meat Probes | Light | Primer Motor | Recipe Mode |
| ----- | -------------: | -------------: | -----------: | :---: | :-----------: | :---------: |
"""


def _yesno(value: bool) -> str:
    return "✅" if value else "—"


def main() -> None:
    """Generates the supported grills doc."""
    lines = [HEADER]
    for grill in sorted(grills.get_grills(), key=lambda g: g.name.lower()):
        has_primer = "turn-primer-motor-on" in grill.control_board.commands
        has_recipe = bool(grill.json.get("has_recipe_functionality"))
        min_temp = grill.min_temp if grill.min_temp is not None else "?"
        max_temp = grill.max_temp if grill.max_temp is not None else "?"
        lines.append(
            f"| {grill.name} | {min_temp} | {max_temp} | {grill.meat_probes} "
            f"| {_yesno(grill.has_lights)} | {_yesno(has_primer)} "
            f"| {_yesno(has_recipe)} |\n"
        )

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text("".join(lines))
    print(f"Wrote {OUTPUT} ({len(lines) - 1} grills)")


if __name__ == "__main__":
    main()
